/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jp_assignment;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lynne
 */
public final class room extends javax.swing.JFrame {

    /**
     * Creates new form room
     * @throws IOException
     */
    public room() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        importAll();
        importCategorised();
    }
    
    public void importAll() throws IOException {
        fileHandle file = new fileHandle("rooms.txt");
        int ID = file.getLineNumber();
        nextID.setText(String.valueOf(ID));
        
        // Reset table
        DefaultTableModel model = (DefaultTableModel)allRoomsTable.getModel();
        model.setRowCount(0);
        
        Object[] fileRow = file.readFromFile();
        
        for (var i = 0; i < fileRow.length; i++) {
            String line = fileRow[i].toString().trim();
            String[] dataRow = line.split(", ");
            if (i == 0){
                model.setColumnIdentifiers(dataRow);
            } else {
                model.addRow(dataRow);
            }
        }
    }
    
    public void importCategorised() throws IOException {
        fileHandle file = new fileHandle("rooms.txt");
        int ID = file.getLineNumber();
        nextID.setText(String.valueOf(ID));
        
        // Reset table
        DefaultTableModel availablemodel = (DefaultTableModel)availableRoomsTable.getModel();
        DefaultTableModel reservemodel = (DefaultTableModel)reservedRoomsTable.getModel();
        availablemodel.setRowCount(0);
        reservemodel.setRowCount(0);
        
        Object[] fileRow = file.readFromFile();
        
        for (var i = 0; i < fileRow.length; i++) {
            String line = fileRow[i].toString().trim();
            String[] dataRow = line.split(", ");
            if (i == 0){
                availablemodel.setColumnIdentifiers(dataRow);
                reservemodel.setColumnIdentifiers(dataRow);
            } else if (dataRow[4].equals("True")){
                availablemodel.addRow(dataRow);
            } else if (dataRow[4].equals("False")){
                reservemodel.addRow(dataRow);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jDialog4 = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roomControls = new javax.swing.JTabbedPane();
        allRoomsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addRoomBtn = new javax.swing.JButton();
        roomNumberInput = new javax.swing.JTextField();
        roomViewInput = new javax.swing.JComboBox<>();
        roomTypeInput = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        allRoomsTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        nextID = new javax.swing.JLabel();
        availableRoomsPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        availableRoomsTable = new javax.swing.JTable();
        reservedRoomsPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        reservedRoomsTable = new javax.swing.JTable();
        mainPageBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setText("Jungle Sea Resort Management System");

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rooms");

        roomControls.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        roomControls.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roomControls.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel3.setText("Room Number:");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel4.setText("Room View:");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel5.setText("Room Type:");

        addRoomBtn.setBackground(new java.awt.Color(21, 76, 121));
        addRoomBtn.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        addRoomBtn.setForeground(new java.awt.Color(255, 255, 255));
        addRoomBtn.setText("Add Room");
        addRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomBtnActionPerformed(evt);
            }
        });

        roomNumberInput.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        roomNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberInputActionPerformed(evt);
            }
        });

        roomViewInput.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        roomViewInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jungle View", "Sea View" }));

        roomTypeInput.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        roomTypeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Quad", "Queen", "King" }));

        allRoomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(allRoomsTable);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel8.setText("ID:");

        nextID.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        nextID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextID.setText("id");

        javax.swing.GroupLayout allRoomsPanelLayout = new javax.swing.GroupLayout(allRoomsPanel);
        allRoomsPanel.setLayout(allRoomsPanelLayout);
        allRoomsPanelLayout.setHorizontalGroup(
            allRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allRoomsPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(allRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRoomBtn)
                    .addGroup(allRoomsPanelLayout.createSequentialGroup()
                        .addGroup(allRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(allRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(allRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(roomViewInput, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(roomNumberInput)
                                .addComponent(roomTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        allRoomsPanelLayout.setVerticalGroup(
            allRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allRoomsPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(allRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nextID))
                .addGap(18, 18, 18)
                .addGroup(allRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(allRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomViewInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(allRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allRoomsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(roomTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(addRoomBtn)
                .addGap(125, 125, 125))
            .addGroup(allRoomsPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roomControls.addTab("All Rooms", allRoomsPanel);

        availableRoomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(availableRoomsTable);

        javax.swing.GroupLayout availableRoomsPanelLayout = new javax.swing.GroupLayout(availableRoomsPanel);
        availableRoomsPanel.setLayout(availableRoomsPanelLayout);
        availableRoomsPanelLayout.setHorizontalGroup(
            availableRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableRoomsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        availableRoomsPanelLayout.setVerticalGroup(
            availableRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableRoomsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        roomControls.addTab("Available Rooms", availableRoomsPanel);

        reservedRoomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(reservedRoomsTable);

        javax.swing.GroupLayout reservedRoomsPanelLayout = new javax.swing.GroupLayout(reservedRoomsPanel);
        reservedRoomsPanel.setLayout(reservedRoomsPanelLayout);
        reservedRoomsPanelLayout.setHorizontalGroup(
            reservedRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservedRoomsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        reservedRoomsPanelLayout.setVerticalGroup(
            reservedRoomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservedRoomsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        roomControls.addTab("Reserved Rooms", reservedRoomsPanel);

        mainPageBtn.setBackground(new java.awt.Color(21, 76, 121));
        mainPageBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        mainPageBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainPageBtn.setText("Main Page");
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(348, 348, 348)
                                .addComponent(jLabel2))
                            .addComponent(mainPageBtn))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(mainPageBtn)
                .addGap(18, 18, 18)
                .addComponent(roomControls, javax.swing.GroupLayout.PREFERRED_SIZE, 423, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNumberInputActionPerformed

    private void addRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomBtnActionPerformed
        //Get Room number, room view, room type (user input)
        String roomNum = roomNumberInput.getText();
        String roomView = roomViewInput.getSelectedItem().toString();
        String roomType = roomTypeInput.getSelectedItem().toString();
        String id = nextID.getText();

        String[] data = {id, roomNum, roomView, roomType, "True"};

        fileHandle insert = new fileHandle("rooms.txt");

        if (insert.writeToFile(data)) {
            JOptionPane.showMessageDialog(this, "New room data has been added successfully.", "Insertion Successfull", JOptionPane.INFORMATION_MESSAGE);
            try {
                importAll();
            } catch (IOException ex) {
                Logger.getLogger(room.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                importCategorised();
            } catch (IOException ex) {
                Logger.getLogger(room.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "An error has occured while inserting!\nPlease try again.", "Insertion Failed", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addRoomBtnActionPerformed

    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
        new index().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainPageBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new room().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(room.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomBtn;
    private javax.swing.JPanel allRoomsPanel;
    private javax.swing.JTable allRoomsTable;
    private javax.swing.JPanel availableRoomsPanel;
    private javax.swing.JTable availableRoomsTable;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JLabel nextID;
    private javax.swing.JPanel reservedRoomsPanel;
    private javax.swing.JTable reservedRoomsTable;
    private javax.swing.JTabbedPane roomControls;
    private javax.swing.JTextField roomNumberInput;
    private javax.swing.JComboBox<String> roomTypeInput;
    private javax.swing.JComboBox<String> roomViewInput;
    // End of variables declaration//GEN-END:variables
}
